import { MigrationInterface, QueryRunner } from "typeorm";

export class Wayu1778157329109 implements MigrationInterface {
    name = 'Wayu1778157329109'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_11c91735b88837592a524662e69"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('superAdmin', 'admin', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."users_logintype_enum" AS ENUM('email', 'password')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "fullName" character varying(64) NOT NULL, "login" character varying(64) NOT NULL, "loginType" "public"."users_logintype_enum" NOT NULL, "password" character varying(128), "birthDate" date, "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_2d443082eccd5198f95f2a36e2c" UNIQUE ("login"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "representatives" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "fullName" character varying(64) NOT NULL, "image" character varying(128) NOT NULL, "email" character varying(64) NOT NULL, "phoneNumber" character varying(16) NOT NULL, "resume" text NOT NULL, CONSTRAINT "PK_80e9af53802d5e0376d1ae8f68c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD "tagsId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vacancies" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "vacancies" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vacancies" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "vacancies" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_5707a4abd8063c6494064d22d05"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "vacancyId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tags" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tags" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tags" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tags" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsCategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "newsCategories" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsCategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "newsCategories" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_ec93cf21dec41ec5ca617512ef0"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "countryId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "representativeId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookCategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "bookCategories" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookCategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "bookCategories" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_54f49efe2dd4d2850e736e9ab86"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_a0f13454de3df36e337e01dbd55"`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "authorId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "categoryId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "UQ_f1728b7ae26a61b0e695217ff16"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "transactionId"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "transactionId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "UQ_f1728b7ae26a61b0e695217ff16" UNIQUE ("transactionId")`);
        await queryRunner.query(`ALTER TABLE "donations" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "donations" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "donations" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "donations" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "eventCategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "eventCategories" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "eventCategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "eventCategories" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_2f7107d3528147b9237b6e2a2fe"`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "categoryId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usefulLinks" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "usefulLinks" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usefulLinks" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "usefulLinks" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "socialLinks" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "socialLinks" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "socialLinks" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "socialLinks" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "staticInfo" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "staticInfo" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "staticInfo" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "staticInfo" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "instagramPosts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "instagramPosts" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "instagramPosts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "instagramPosts" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "languages" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "languages" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "languages" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "languages" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_5707a4abd8063c6494064d22d05" FOREIGN KEY ("vacancyId") REFERENCES "vacancies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_ec93cf21dec41ec5ca617512ef0" FOREIGN KEY ("countryId") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_11c91735b88837592a524662e69" FOREIGN KEY ("representativeId") REFERENCES "representatives"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_54f49efe2dd4d2850e736e9ab86" FOREIGN KEY ("authorId") REFERENCES "authors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_a0f13454de3df36e337e01dbd55" FOREIGN KEY ("categoryId") REFERENCES "bookCategories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_2f7107d3528147b9237b6e2a2fe" FOREIGN KEY ("categoryId") REFERENCES "eventCategories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_2f7107d3528147b9237b6e2a2fe"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_a0f13454de3df36e337e01dbd55"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_54f49efe2dd4d2850e736e9ab86"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_11c91735b88837592a524662e69"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_ec93cf21dec41ec5ca617512ef0"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_5707a4abd8063c6494064d22d05"`);
        await queryRunner.query(`ALTER TABLE "languages" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "languages" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "languages" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "languages" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "instagramPosts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "instagramPosts" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "instagramPosts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "instagramPosts" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "staticInfo" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "staticInfo" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "staticInfo" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "staticInfo" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "socialLinks" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "socialLinks" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "socialLinks" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "socialLinks" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usefulLinks" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "usefulLinks" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usefulLinks" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "usefulLinks" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "categoryId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "events" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_2f7107d3528147b9237b6e2a2fe" FOREIGN KEY ("categoryId") REFERENCES "eventCategories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "eventCategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "eventCategories" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "eventCategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "eventCategories" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "donations" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "donations" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "donations" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "donations" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "UQ_f1728b7ae26a61b0e695217ff16"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "transactionId"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "transactionId" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "UQ_f1728b7ae26a61b0e695217ff16" UNIQUE ("transactionId")`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "categoryId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "authorId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_a0f13454de3df36e337e01dbd55" FOREIGN KEY ("categoryId") REFERENCES "bookCategories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_54f49efe2dd4d2850e736e9ab86" FOREIGN KEY ("authorId") REFERENCES "authors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookCategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "bookCategories" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookCategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "bookCategories" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "authors" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "authors" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "questions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "questions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "representativeId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" ALTER COLUMN "countryId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_ec93cf21dec41ec5ca617512ef0" FOREIGN KEY ("countryId") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsCategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "newsCategories" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsCategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "newsCategories" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tags" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tags" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tags" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tags" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "vacancyId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_5707a4abd8063c6494064d22d05" FOREIGN KEY ("vacancyId") REFERENCES "vacancies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vacancies" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "vacancies" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vacancies" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "vacancies" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP COLUMN "tagsId"`);
        await queryRunner.query(`DROP TABLE "representatives"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_logintype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_11c91735b88837592a524662e69" FOREIGN KEY ("representativeId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
